export default {
  General: {
    title: `General`,
    description: `Interaction with all things solely related to the application.`,
    tags: [`Core`, `Misc`],
    icon: `mdi-application-brackets`,
  },
  Commands: {
    title: `Commands`,
    description: `Change the state of commands.`,
    tags: [`Core`, `Commands`],
    icon: `mdi-apple-keyboard-command`,
  },
  Groups: {
    title: `Groups`,
    description: `Change user groups.`,
    tags: [`Core`, `Users`],
    icon: `mdi-folder`,
  },
  ServersAndClients: {
    title: `Servers and Clients`,
    description: `Connect Streamer.bot to servers and clients.`,
    tags: [`Core`, `Servers`, `Clients`],
    icon: `mdi-server`,
  },
  GlobalVariables: {
    title: `Global Variables`,
    description: `Control your global variables.`,
    tags: [`Core`, `Cariables`],
    icon: `mdi-earth`,
  },
  YouTube: {
    title: `YouTube`,
    description: `Enhance your YouTube livestreams.`,
    tags: [`Stream Apps`, `Livestreams`],
    icon: `mdi-youtube`,
  },
  Twitch: {
    title: `Twitch`,
    description: `Enhance your Twitch livestreams.`,
    tags: [`Stream Apps`, `Livestreams`],
    icon: `mdi-twitch`,
  },
  OBSStudio: {
    title: `OBS Studio`,
    description: `Take your OBS to the next level.`,
    tags: [`Stream Apps`, `Broadcasting Software`],
    image: `https://streamer.bot/img/integrations/obs.svg`,
  },
  StreamLabsDesktop: {
    title: `StreamLabs Desktop`,
    description: `Control your StreamLabs Desktop.`,
    tags: [`Stream Apps`, `Broadcasting Software`],
    image: `https://streamer.bot/img/integrations/streamlabs-desktop.png`,
  },
  Discord: {
    title: `Discord`,
    description: `Send webhooks to Discord.`,
    tags: [`Integrations`, `Webhooks`],
    image: `https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a69f118df70ad7828d4_icon_clyde_blurple_RGB.svg`,
  },
  Speakerbot: {
    title: `Speaker.bot`,
    description: `Send TTS requests to Speaker.bot.`,
    tags: [`Integrations`, `TTS`],
    image: `https://streamer.bot/twitchspeaker/logo.svg`,
  },
  LumiaStream: {
    title: `Lumia Stream`,
    description: `Control your lights.`,
    tags: [`Integrations`, `Lights`],
    image: `https://streamer.bot/img/integrations/lumia.png`,
  },
  VoiceMod: {
    title: `VoiceMod`,
    description: `Control your voice.`,
    tags: [`Integrations`, `Voice`],
    image: `https://streamer.bot/img/integrations/voicemod.png`,
  },
}
