export default {
  General: {
    title: `General`,
    description: `Interaction with all things solely related to the application.`,
    tags: [`Core`, `Misc`],
    icon: `mdi-application-brackets`,
  },
  Commands: {
    title: `Commands`,
    description: `Change the state of commands.`,
    tags: [`Core`, `Commands`],
    icon: `mdi-apple-keyboard-command`,
  },
  Groups: {
    title: `Groups`,
    description: `Change user groups.`,
    tags: [`Core`, `Users`],
    icon: `mdi-folder`,
  },
  ServersAndClients: {
    title: `Servers and Clients`,
    description: `Connect Streamer.bot to servers and clients.`,
    tags: [`Core`, `Servers`, `Clients`],
    icon: `mdi-server`,
  },
  GlobalVariables: {
    title: `Global Variables`,
    description: `Control your global variables.`,
    tags: [`Core`, `Variables`],
    icon: `mdi-earth`,
  },
  YouTube: {
    title: `YouTube`,
    description: `Enhance your YouTube livestreams.`,
    tags: [`Stream Apps`, `Livestreams`],
    icon: `mdi-youtube`,
  },
  Twitch: {
    title: `Twitch`,
    description: `Enhance your Twitch livestreams.`,
    tags: [`Stream Apps`, `Livestreams`],
    icon: `mdi-twitch`,
  },
  OBSStudio: {
    title: `OBS Studio`,
    description: `Take your OBS to the next level.`,
    tags: [`Stream Apps`, `Broadcasting Software`],
    image: `https://streamer.bot/img/integrations/obs.svg`,
  },
  StreamLabsDesktop: {
    title: `StreamLabs Desktop`,
    description: `Control your StreamLabs Desktop.`,
    tags: [`Stream Apps`, `Broadcasting Software`],
    image: `https://streamer.bot/img/integrations/streamlabs-desktop.png`,
  },
  Speakerbot: {
    title: `Speaker.bot`,
    description: `Send TTS requests to Speaker.bot.`,
    tags: [`Integrations`, `TTS`],
    image: `https://streamer.bot/twitchspeaker/logo.svg`,
  },
  StreamDeck: {
    title: `Stream Deck`,
    description: `Manage your Streamer.bot buttons from your StreamDeck.`,
    tags: [`Integrations`, `Remote Control`],
    image: `https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/2de874ee-0fa4-4ba4-bda6-45d335b504c5/dbaxo06-4f6b5105-f590-4975-882e-8daa2267cb9b.png/v1/fill/w_512,h_512/elgato_gamecapture_hd_new_honeycomb_rainmeter_skin_by_theultimateslime_dbaxo06-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvMmRlODc0ZWUtMGZhNC00YmE0LWJkYTYtNDVkMzM1YjUwNGM1XC9kYmF4bzA2LTRmNmI1MTA1LWY1OTAtNDk3NS04ODJlLThkYWEyMjY3Y2I5Yi5wbmciLCJ3aWR0aCI6Ijw9NTEyIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.03FSOtlDBFzKICN891uOV9uMuuv4K6pUovGKuwV3Zj0`,
  },
  Discord: {
    title: `Discord`,
    description: `Send webhooks to Discord.`,
    tags: [`Integrations`, `Webhooks`],
    image: `https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a69f118df70ad7828d4_icon_clyde_blurple_RGB.svg`,
  },
  LumiaStream: {
    title: `Lumia Stream`,
    description: `Control your lights.`,
    tags: [`Integrations`, `Lights`],
    image: `https://streamer.bot/img/integrations/lumia.png`,
  },
  VoiceMod: {
    title: `VoiceMod`,
    description: `Control your voice.`,
    tags: [`Integrations`, `Voice`],
    image: `https://streamer.bot/img/integrations/voicemod.png`,
  },
}
